USE AplicatieCinematograf
GO

-- Dirty Reads
-- PROBLEMA: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:15';
SELECT * FROM Clienti;
COMMIT TRAN

-- SOLUTIE: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:15';
SELECT * FROM Clienti;
COMMIT TRAN


-- Non-Repeatable Reads
-- PROBLEMA: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:15';
SELECT * FROM Clienti;
COMMIT TRAN

-- SOLUTIE: SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Clienti;
WAITFOR DELAY '00:00:15';
SELECT * FROM Clienti;
COMMIT TRAN


-- Phantom Reads
-- PROBLEMA: SET TRANSACTION ISOLATION LEVEL TO REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Clienti
WAITFOR DELAY '00:00:15'
SELECT * FROM Clienti
COMMIT TRAN

-- SOLUTIE: SET TRANSACTION ISOLATION LEVEL TO SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Clienti
WAITFOR DELAY '00:00:15'
SELECT * FROM Clienti
COMMIT TRAN


-- Deadlock

BEGIN TRAN
UPDATE PreferinteClienti SET numeActorPreferat='T2:Deadlock Preferinte' WHERE numeDirectorPreferat='Preferinte Deadlock'
WAITFOR DELAY '00:00:10'
UPDATE Clienti SET nume='T2:Deadlock Clienti' WHERE dataNasterii='2003-05-19';
COMMIT TRAN